[package]
name = "raytracer"
version = "0.1.0"
authors = ["Aymeric Beringer <aymeric.beringer@epita.fr>"]

[dependencies]
png = "0.11.0"
rayon = "1.0.0"
rand = "0.4.2"

[profile.release]
debug = true
